### ISSUE TITLE
No Error Message when trying to login as an unresigtered user

### ISSUE THREAD

**Issue by Hasnainyaqoob** [KaushalNijhawan/QuickChat#16]

**Comment by hashiqumer97** [comment]
Expected results - An error message should be there on the login if the user is not registered in the system

Actual Results - No error message appears when an unregistered user tries to login to system

![image](https://user-images.githubusercontent.com/51371528/235798824-dbce8eec-6c8e-4ca5-ae18-67070abacb38.png)
